name: Production Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: "Manual Sign & Build"
    if: github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Decode Keystore
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        if: ${{ env.SIGNING_KEY != '' }}
        run: |
          echo "$SIGNING_KEY" | base64 --decode > app/release.jks

      - name: Create local.properties
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        if: ${{ env.SIGNING_KEY != '' }}
        run: |
          echo "signing.storeFilePath=release.jks" >> local.properties
          echo "signing.storePassword=${{ secrets.STORE_PASSWORD }}" >> local.properties
          echo "signing.keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "signing.keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Build Production Release (APK & AAB)
        run: ./gradlew :app:bundleProdRelease :app:assembleProdRelease --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prod-release-artifacts
          path: |
            app/build/outputs/apk/prod/release/*.apk
            app/build/outputs/bundle/prodRelease/*.aab
